### ISSUE TITLE
Traducir reference.md

### ISSUE THREAD

**Issue by orchid00** [Carpentries-ES/python-ecology-lesson-es#16]
:+1: :tada: ¡En primer lugar, gracias por tomarte el tiempo para contribuir! :tada: :+1:

Éste repositorio está siendo traducido y nos gustaría mucho que puedas contribuir. Lo siguiente es un conjunto de pautas, no reglas, que hemos desarrollado para otros proyectos de traducción y nos han sido muy útiles para tener una traducción homogénea. [Convenciones](https://github.com/Carpentries-ES/board/blob/master/Convenciones_Traduccion.md).

Aquí puedes comentar sobre preguntas y progreso en la tradución de este episodio.

Episodio: [Reference.md](https://github.com/Carpentries-ES/python-ecology-lesson-es/blob/gh-pages/reference.md)

**Comment by raynamharris** [comment]
enlace correcto: [reference.md](https://github.com/Carpentries-ES/python-ecology-lesson-es/blob/gh-pages/reference.md)

**Comment by chekos** [comment]
yo puedo traducir este también si no lo ha tomado alguien mas

**Comment by orchid00** [comment]
Si porfa! si no hay un comentario es que esta libre ;)

**Comment by orchid00** [comment]
@chekos si tienes cualquier duda avisame

**Comment by chekos** [comment]
@orchid00 acabo de darle la primera pasada al archivo pero ya que termine me di cuenta que son muchos terminos tecnicos y tal vez quieran manter el nombre en ingles y nomas traducir la definicion?

supongo que eso será en la revisión :stuck_out_tongue_closed_eyes:

**Comment by arredondo23** [comment]
@orchid00 Me puedo hacer cargo de la traducción de la referencia :)

**Comment by orchid00** [comment]
hola @arredondo23 ya esta traducida por @chekos puedes ver arriba los comentarios
@chekos disculpa que no te di las convenciones https://github.com/Carpentries-ES/board/blob/master/Convenciones_Traduccion.md puedes revisar los terminos tecnicos. 
luego @arredondo23 podrias revisar y editar en cuanto sea necesario.  
aqui hay un link que te puede ayudar https://help.github.com/articles/reviewing-proposed-changes-in-a-pull-request/

**Comment by orchid00** [comment]
Gracias! Ya estan en el wall of fame :D https://github.com/Carpentries-ES/python-ecology-lesson-es/blob/gh-pages/fechas-progreso.md

**Comment by orchid00** [comment]
Gracias estoy cerrando este issue con el merge de https://github.com/Carpentries-ES/python-ecology-lesson-es/pull/36#issuecomment-438945480
