### ISSUE TITLE
Traducir setup.md

### ISSUE THREAD

**Issue by orchid00** [Carpentries-ES/python-ecology-lesson-es#17]
:+1: :tada: ¡En primer lugar, gracias por tomarte el tiempo para contribuir! :tada: :+1:

Éste repositorio está siendo traducido y nos gustaría mucho que puedas contribuir. Lo siguiente es un conjunto de pautas, no reglas, que hemos desarrollado para otros proyectos de traducción y nos han sido muy útiles para tener una traducción homogénea. [Convenciones](https://github.com/Carpentries-ES/board/blob/master/Convenciones_Traduccion.md).

Aquí puedes comentar sobre preguntas y progreso en la tradución de este episodio.

Episodio: [setup.md](https://github.com/Carpentries-ES/python-ecology-lesson-es/blob/gh-pages/setup.md).

**Comment by raynamharris** [comment]
listo para revisar!  #37

**Comment by orchid00** [comment]
Great! lo voy a revisar

**Comment by orchid00** [comment]
Gracias, this is merged with PR https://github.com/Carpentries-ES/python-ecology-lesson-es/pull/37
