### ISSUE TITLE
Traducir jupyter_notebooks.md

### ISSUE THREAD

**Issue by orchid00** [Carpentries-ES/python-ecology-lesson-es#19]
:+1: :tada: ¡En primer lugar, gracias por tomarte el tiempo para contribuir! :tada: :+1:

Éste repositorio está siendo traducido y nos gustaría mucho que puedas contribuir. Lo siguiente es un conjunto de pautas, no reglas, que hemos desarrollado para otros proyectos de traducción y nos han sido muy útiles para tener una traducción homogénea. [Convenciones](https://github.com/Carpentries-ES/board/blob/master/Convenciones_Traduccion.md).

Aquí puedes comentar sobre preguntas y progreso en la tradución de este episodio.

Episodio: [ jupyter_notebooks.md](https://github.com/Carpentries-ES/python-ecology-lesson-es/blob/gh-pages/_extras/jupyter_notebooks.md)

**Comment by chekos** [comment]
¡Yo quiero hacer este!

**Comment by orchid00** [comment]
Super! gracias!

**Comment by chekos** [comment]
una duda:
__cell__ en jupyter notebook lo traducimos a "celda" o lo dejamos __cell__? Por ser un término técnico asumo que se quedaría __cell__.

de cualquier manera estaría bueno agregar la decisión a [convenciones](https://github.com/Carpentries-ES/board/blob/master/Convenciones_Traduccion.md)

**Comment by orchid00** [comment]
@chekos a mi me parece que celda suena bien @miguelgondu como lo dices tu?
Agrego a miguel por que el enseña Python en español muy seguido

**Comment by miguelgondu** [comment]
¡Es una buena pregunta!, a pesar de ser un término técnico, yo siempre lo he mencionado como "celda" en mis clases, tipo "presionamos 'a' para crear una nueva celda arriba, presionamos 'b' para crear una nueva celda abajo" y así. No sé. ¿Qué opinan ustedes?, tal vez es algo del español de Colombia que hace que para mí tenga sentido usar "celda".

**Comment by miguelgondu** [comment]
@orchid00 ¡con gusto!, le reservaré un poco de tiempo esta semana.

**Comment by orchid00** [comment]
Gracias @miguelgondu
