### ISSUE TITLE
Crear una pagina de progreso con fechas

### ISSUE THREAD

**Issue by orchid00** [Carpentries-ES/python-ecology-lesson-es#4]
Crear una pagina de progreso con fechas

**Comment by orchid00** [comment]
@raynamharris ideally this will be a table that everyone can see, but maybe restrict access of writing.

**Comment by raynamharris** [comment]
vea #24

**Comment by orchid00** [comment]
Great @raynamharris!
Cuando terminemos de traducir agregaremos las columnas de revisor fecha de inicio y fecha de entrega :)
