### ISSUE TITLE
Traducir CONTRIBUTORS.md

### ISSUE THREAD

**Issue by orchid00** [Carpentries-ES/python-ecology-lesson-es#49]
:+1: :tada: ¡En primer lugar, gracias por tomarte el tiempo para contribuir! :tada: :+1:

Éste repositorio está siendo traducido y nos gustaría mucho que puedas contribuir. Lo siguiente es un conjunto de pautas, no reglas, que hemos desarrollado para otros proyectos de traducción y nos han sido muy útiles para tener una traducción homogénea. [Convenciones](https://github.com/Carpentries-ES/board/blob/master/Convenciones_Traduccion.md).

Aquí puedes comentar sobre preguntas y progreso en la tradución de este episodio.

Episodio: [CONTRIBUTORS.md](https://github.com/Carpentries-ES/python-ecology-lesson-es/edit/gh-pages/_extras/CONTRIBUTORS.md)

**Comment by orchid00** [comment]
Además de traducir, quisiera que todas las personas involucradas en la traducción figuren en este archivo.
Información https://github.com/Carpentries-ES/python-ecology-lesson-es/blob/gh-pages/fechas-progreso.md

**Comment by orchid00** [comment]
@LUS24 y @chekos quisiera agregarlos a este archivo de contribuidores, pero no sé sus nombres completos :stuck_out_tongue_closed_eyes:

**Comment by chekos** [comment]
😂 me llamo Sergio Sánchez ¡gracias!

**Comment by LUS24** [comment]
@orchid00 , Leonardo Ulises Spairani :-)

**Comment by orchid00** [comment]
Gracias Sergio y Leonardo!

**Comment by orchid00** [comment]
Working on the list here

[Alejandra Gonzalez-Beltran](https://github.com/agbeltran), 
[](https://github.com/arredondo23)
[](https://github.com/chekos)
[](https://github.com/ComplejoC)
[](https://github.com/enricescorsa)
[](https://github.com/fergarciafer)
[](https://github.com/Helysalgado)
[](https://github.com/jmbarrios)
[](https://github.com/LauCIFASIS)
[](https://github.com/LUS24)
[](https://github.com/miguelgondu)
[](https://github.com/NPalopoli)
[](https://github.com/orchid00)
[](https://github.com/raynamharris)
[](https://github.com/rzayas)
[](https://github.com/spencerbh)
[](https://github.com/spereyra)
[](https://github.com/welozano)

**Comment by rzayas** [comment]
@orchid00 ya hice la traducción, para esto hice un repositorio nuevo, un branch y antes de hacer el commit hay que revisar el trabajo. No estoy seguro si puedes ver los cambios al estar en mi repositorio. De ser así, ¿hago el commit para que otros puedan ver los cambios y revisarlos?
saludos :+1:

**Comment by orchid00** [comment]
Muchas gracias @rzayas Todo lo que histe esta muy bien, desde tu fork (copy del repositorio) tienes q mandar los cambios al repositorio de Carpentries-ES de esta manera: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by welozano** [comment]
Wilson Lozano-Rolón

**Comment by orchid00** [comment]
HolA!!! 
Ya estamos casi listos con la traduccion, por favor revisen este archivo y que sus nombres esten bien, si es necesario hacer cambios manden un PR. 
Muchiiiiisimas gracias 👍 🥇 

@agbeltran
@arredondo23
@chekos
@ComplejoC
@enricescorsa
@fergarciafer
@Helysalgado
@jmbarrios
@LauCIFASIS
@LUS24
@miguelgondu
@NPalopoli
@orchid00
@raynamharris
@rzayas
@spencerbh
@spereyra
@welozano
@nohemihuanca 
@monialo2000
https://carpentries-es.github.io/python-ecology-lesson-es/contributors/

**Comment by LauCIFASIS** [comment]
Tienes razón Fernando, hay un rollo con la palabra "contribuidores" .  

Que opinan si la cambiamos por "colaboradores" ??? 

Saludos 

Laura.- 

El 22-11-2018 22:28, Fernando Garcia escribió:

> Buenas noches, 
> 
> Quizá esta discusión ya la hayan tenido en otro momento y hayan llegado a una resolución pues en el documento de Convenciones, se propone traducir la palabra "contributor" como "contribuidor" y no "contribuyente". Sin embargo, estuve mirando el sitio de la RAE en el cual la palabra "contribuidor" es aceptada como adjetivo, no como sustantivo. Aquí estaríamos usando como sustantivo una palabra no aceptada por la RAE. Les dejo el link de la RAE: http://dle.rae.es/?id=AeOHcvQ 
> 
> Un saludo.
> Fernando. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

  

Links:
------
[1]
https://github.com/Carpentries-ES/python-ecology-lesson-es/issues/49#issuecomment-441141027
[2]

**Comment by fergarciafer** [comment]
Hola @LauCIFASIS !

"Colaboradores" me parece la alternativa mas acertada.

**Comment by agbeltran** [comment]
+1 para colaboradores

**Comment by monialo2000** [comment]
+1 colaboradores

**Comment by spereyra** [comment]
De acuerdo con colaboradores

**Comment by spereyra** [comment]
De acuerdo con colaboradores

**Comment by arredondo23** [comment]
Sí +1 para colaboradores

**Comment by orchid00** [comment]
Muy bien, llamo a esto concenso! diremos colaboradores! 
Voy a cambiar las convenciones y el archivo.
A todo esto, se fijaron si sus nombres estan bien escritos? 
Gracias a tod@s!

**Comment by Helysalgado** [comment]
Me gusta colaboradores.

contribuyente me suena mas como impuestos y hacienda.

saludos

**Comment by orchid00** [comment]
Listo https://github.com/Carpentries-ES/python-ecology-lesson-es/commits/gh-pages/_extras/CONTRIBUTORS.md
